декоративные эллементы главной страницы
htmlacademy-htmlcss/1580379-nerds-29 pull request #11
Opened 2020-10-31 13:35 UTC by opg-x

2020-10-31 18:26 UTC, raccoonroman requested changes

2020-10-31 18:26 UTC, raccoonroman commented on css/styles.css
> +  height: 308px;
высоту убрать

2020-10-31 18:26 UTC, raccoonroman commented on css/styles.css
> +  height: 50px;
высоту убрать

2020-10-31 18:26 UTC, raccoonroman commented on css/styles.css
> +.modal-comunication h2{
```suggestion
.modal-comunication h2 {
```

2020-10-31 18:26 UTC, raccoonroman commented on css/styles.css
> +  margin-right: 40px;
пункты формы лучше сделать списком из 3х элементов, и разместить гридами, используя свойство gap

2020-10-31 18:26 UTC, raccoonroman commented on css/styles.css
> +  padding: 16px
```suggestion
  padding: 16px;
```

2020-10-31 18:26 UTC, raccoonroman commented on css/styles.css
> +  height: 118px;
высоту убрать

2020-10-31 18:26 UTC, raccoonroman commented on css/styles.css
> +  height: 50px;
высоту убрать

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +          <li class="web-item">
```suggestion
          <li class="service-item service-item-web">
```

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +          <li class="app-item">
```suggestion
          <li class="service-item service-item-app">
```

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +          <li class="presentation-item">
```suggestion
          <li class="service-item service-item-presentation">
```

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +          <li class="presentation-item">
... где в `service-item` будут общие стили для трех пунктов, а в `service-item-presentation` - специфичные, только для него

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +            <a class="footer-social-button vkontakte" href="#">
классы vkontakte, facebook и т. д. можно убрать, так как стили на них не навешаны (картинки ты вывел контентом)

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +      <p class="appointment-item">
сделай список (ul, li) и для li - класс `communication-form-item`

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +        <input id="letter" type="text" name="userletter" placeholder="В свободой форме">
это тег textarea https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

2020-10-31 18:26 UTC, raccoonroman commented on index.html
> +    </fieldset>
открывающего тега fieldset не вижу, проверь валидатором https://validator.w3.org/nu/

2020-11-04 18:43 UTC, opg-x commented on css/styles.css
> +  margin-right: 45px;
исправил

2020-11-04 18:45 UTC, opg-x commented on css/styles.css
> +  background-image: url("/img/bin-icon.svg");
исправил

2020-11-04 18:47 UTC, opg-x commented on css/styles.css
> +  left: 17px;
исправил

2020-11-04 18:52 UTC, opg-x commented on css/styles.css
> +  line-height: 50px;
исправил

2020-11-04 18:55 UTC, opg-x commented on css/styles.css
> +  box-shadow: inset 0px 3px 0px rgba(0, 1, 1, 0.1);
исправил

2020-11-04 18:57 UTC, opg-x commented on css/styles.css
> +  height: 50px;
исправил на мин-хай

2020-11-04 19:00 UTC, opg-x commented on css/styles.css
> +  height: 431px;
исправил

2020-11-04 19:00 UTC, opg-x commented on css/styles.css
> +  background-image: url("/img/slide1.png");
исправил

2020-11-04 19:07 UTC, opg-x commented on css/styles.css
> +  left: 526px;
исправил

2020-11-04 19:07 UTC, opg-x commented on css/styles.css
> +  width: 88px;
исправил

2020-11-04 19:07 UTC, opg-x commented on css/styles.css
> +  border: 0px;
исправил

2020-11-04 19:09 UTC, opg-x commented on css/styles.css
> +  content: '';
исправил

2020-11-04 19:09 UTC, opg-x commented on css/styles.css
> +  border: 2px solid #C1C1C1;
исправил

2020-11-04 19:56 UTC, opg-x commented on css/styles.css
> +.service-list-content-img {
сделал

2020-11-04 19:56 UTC, opg-x commented on css/styles.css
> +  background-image: url("/img/web.jpg");
исправил

2020-11-04 19:57 UTC, opg-x commented on css/styles.css
> +  height: 50px;
есть!

2020-11-04 19:58 UTC, opg-x commented on css/styles.css
> +  padding: 73px 0 40px 0;
исправил

2020-11-04 19:59 UTC, opg-x commented on css/styles.css
> +.about-us-services-list li{
исправил

2020-11-04 20:02 UTC, opg-x commented on css/styles.css
> +  top: 50%;
сделал

2020-11-04 20:02 UTC, opg-x commented on css/styles.css
> +  margin: 40px 0 35px 0;
исправил

2020-11-04 20:04 UTC, opg-x commented on css/styles.css
> +  height: 180px;
исправил

2020-11-04 20:04 UTC, opg-x commented on css/styles.css
> +  height: 100%;
убрал

2020-11-04 20:06 UTC, opg-x commented on css/styles.css
> +  height: 308px;
убрал

2020-11-04 20:06 UTC, opg-x commented on css/styles.css
> +  height: 50px;
убрал

2020-11-04 20:06 UTC, opg-x commented on css/styles.css
> +.modal-comunication h2{
исправил

2020-11-04 20:08 UTC, opg-x commented on css/styles.css
> +  padding: 16px
исправил

2020-11-04 20:08 UTC, opg-x commented on css/styles.css
> +  height: 118px;
убрал

2020-11-04 20:10 UTC, opg-x commented on css/styles.css
> +  height: 50px;
изменил на мин-хай

2020-11-04 20:10 UTC, opg-x commented on index.html
> +          <li class="web-item">
заменил

2020-11-04 20:10 UTC, opg-x commented on index.html
> +          <li class="app-item">
заменил

2020-11-04 20:16 UTC, opg-x commented on index.html
> +          <li class="presentation-item">
исправил

2020-11-04 20:16 UTC, opg-x commented on index.html
> +            <a class="footer-social-button vkontakte" href="#">
ок

2020-11-04 20:26 UTC, opg-x commented on index.html
> +        <input id="letter" type="text" name="userletter" placeholder="В свободой форме">
исправил

2020-11-04 20:54 UTC, opg-x commented on index.html
> +      <p class="appointment-item">
сделал

2020-11-04 20:58 UTC, opg-x commented on index.html
> +    </fieldset>
добавил

2020-11-05 18:27 UTC, raccoonroman approved these changes

2020-11-05 18:27 UTC, raccoonroman commented on css/styles.css
> +.about-us .about-us-services-list-title {
зачем зря увеличивать вес селектора, можно просто:
```suggestion
.about-us-services-list-title {
```

2020-11-05 18:27 UTC, raccoonroman commented on css/styles.css
> +  height: 50px;
не убрал

2020-11-05 18:27 UTC, raccoonroman commented on css/styles.css
> +  justify-content: space-between;
всегда должны быть отступы между элементами. Будет иконок 4 - они слипнуться. Вообще, space-between используется в редких случаях. Здесь лучше использовать магрины в пикслях для `.footer-social-list li`

2020-11-05 18:27 UTC, raccoonroman commented on css/styles.css
> +  padding: 16px 16px;
```suggestion
  padding: 16px;
```

2020-11-05 18:27 UTC, raccoonroman commented on index.html
> +              <img src="img/vk-icon.svg">
нужно указывать атрибуты width, height, alt 
https://up.htmlacademy.ru/htmlcss/29/criteries#d1
https://up.htmlacademy.ru/htmlcss/29/criteries#d28

2020-11-05 18:27 UTC, merged