Первая разметка главной страницы
htmlacademy-htmlcss/1580379-nerds-29 pull request #2
Opened 2020-09-14 21:03 UTC by opg-x

2020-09-15 17:44 UTC, raccoonroman requested changes
Конечно, есть замечания, но на удивление, размечено достаточно неплохо 👍

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +          Математически выверенный дизайн<br />
закрывающие слеши для одиночных тегов не обязательно ставить

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +          Математически выверенный дизайн<br />
```suggestion
          Математически выверенный дизайн<br />
```
```suggestion
          Математически выверенный дизайн<br>
```

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +        <button type="button">Узнать больше</button>
это ссылка

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +      </section>
это слайдер, который состоит из трех слайдов и навигации в виде 3-х точек. Сам слайдер можно сделать дивом либо секцией, внутри которой список для слайдов + список для навигации

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +            <img src="#" alt="Изображение ноутбука" />
эти изображения декоративные, которые нужно выводить стилями, а не через разметку  https://htmlacademy.ru/blog/boost/graphics/content-or-decor-img

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +            <button type="button">Заказать</button>
это ссылка

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +          расчет<br />
Примеры, где допустимо использование br https://prnt.sc/uhtjkc, во всех остальных местах они не нужны

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +            <img src="#" alt="Логотип дизайн-студии Nerds" />
изображение не нужно включать в таблицу

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +            <td colspan="6">с 2004 года Любим точность во всем</td>
этот текст лучше вынести из таблицы

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +            <td>%</td>
`%` это не отдельная ячейка. должно быть так `<td>146<sup>%</sup></td>`

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +            <p>тел. +7 (812) 275-75-75</p>
https://up.htmlacademy.ru/htmlcss/29/criteries#d29

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +            <button>Напишите нам</button>
это ссылка

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +                <img src="#" alt="Вконтакте" />
иконки декоративные https://htmlacademy.ru/blog/boost/graphics/content-or-decor-img

2020-09-15 17:44 UTC, raccoonroman commented on index.html
> +    </main>
тег футер должен быть после секции main, а не внутри нее

2020-09-15 20:02 UTC, opg-x commented on index.html
> +          Математически выверенный дизайн<br />
убрал все закрывающие слеши для одиночных тегов

2020-09-15 20:04 UTC, opg-x commented on index.html
> +        <button type="button">Узнать больше</button>
"Узнать больше" - сделал ссылкой

2020-09-15 21:26 UTC, opg-x commented on index.html
> +      </section>
добавил слайдер

2020-09-15 21:27 UTC, opg-x commented on index.html
> +            <img src="#" alt="Изображение ноутбука" />
убрал изображения <img> из разметки

2020-09-15 21:29 UTC, opg-x commented on index.html
> +            <button type="button">Заказать</button>
заменил кнопки на ссылки

2020-09-15 21:37 UTC, opg-x commented on index.html
> +          расчет<br />
удалил <br> где не нужно, однако про второй слайд слайдера, мне кажется, забыли (там оставил)

2020-09-15 21:43 UTC, opg-x commented on index.html
> +            <img src="#" alt="Логотип дизайн-студии Nerds" />
убрал изображение, чтобы потом вывести его через CSS

2020-09-15 21:44 UTC, opg-x commented on index.html
> +            <td colspan="6">с 2004 года Любим точность во всем</td>
вынес текст из таблицы

2020-09-15 21:47 UTC, opg-x commented on index.html
> +            <td>%</td>
внес % в ячейку с числом, сделал верхним индексом

2020-09-15 22:01 UTC, opg-x commented on index.html
> +            <p>тел. +7 (812) 275-75-75</p>
телефон - теперь ссылка

2020-09-15 22:06 UTC, opg-x commented on index.html
> +            <button>Напишите нам</button>
исправил кнопку на ссылку

2020-09-15 22:08 UTC, opg-x commented on index.html
> +    </main>
теперь секции в норме

2020-09-15 22:18 UTC, opg-x commented on index.html
> +                <img src="#" alt="Вконтакте" />
сделан список ссылок для иконок соцсетей

2020-09-15 22:19 UTC, opg-x commented on index.html
> +          Математически выверенный дизайн<br />
убрал закрывающие слеши для одиночных тегов

2020-09-16 15:29 UTC, raccoonroman requested changes

2020-09-16 15:29 UTC, raccoonroman commented on index.html
> +        <li>кнопка</li>
кнопки (точки) нужно делать тегом button, внутри каждой лишки (li)

2020-09-16 15:29 UTC, raccoonroman commented on index.html
> +        <li>кнопка</li>
и не забывать указывать тип кнопки

2020-09-16 15:29 UTC, raccoonroman commented on index.html
> +        <table>
Логотип сайта обычно является контентным изображением, его можно вернуть в разметку. В данном случае речь шла только про то, чтобы убрать картинку из таблицы

2020-09-16 16:28 UTC, opg-x commented on index.html
> +        <table>
вернул изображение в разметку

2020-09-16 16:33 UTC, opg-x commented on index.html
> +        <li>кнопка</li>
реализовал кнопки через <button type="button">

2020-09-16 18:11 UTC, raccoonroman approved these changes
👍

2020-09-16 18:11 UTC, merged