добавление классов, наложение стилей
htmlacademy-htmlcss/1580379-nerds-29 pull request #4
Opened 2020-09-24 14:42 UTC by opg-x

2020-09-24 18:24 UTC, raccoonroman requested changes
* если учивывать, какие значения свойств уже имеют элементы по умолчанию и вспомнить про наследование, то можно писать гораздо меньше стилей.
* так же нужно отформатировать свой код единообразно, учитывая общепринятые соглашения https://htmlacademy.ru/blog/academy/news/codeguide-why-what-and-how

2020-09-24 18:24 UTC, raccoonroman commented on index.html
> +        <a class="button button-write-us" href="#">Напишите нам</a>
```suggestion
        <a class="button footer-contacts-button" href="#">Напишите нам</a>
```

2020-09-24 18:24 UTC, raccoonroman commented on index.html
> +    <section class="footer-social">
cоц. сети не тянут на целую секцию. Это обычный див. Или вообще этот элемент можно убрать.

2020-09-24 18:24 UTC, raccoonroman commented on css/styles.css
> +  .center h1 {
h1 в данном случае никак не зависит от класса center. Лучше дать заголовку класс и стилизовать по нему. И не увеличивать напрасно специфичность селектора.

2020-09-24 19:03 UTC, opg-x commented on css/styles.css
> +         url("/fonts/roboto.woff2") format("woff2"),
исправил кавычки, пофиксил шрифт

2020-09-24 19:05 UTC, opg-x commented on css/styles.css
> +  :root {
исправил

2020-09-24 19:31 UTC, opg-x commented on css/styles.css
> +
добавил

2020-09-24 19:31 UTC, opg-x commented on css/styles.css
> +      font-family: "Roboto", Arial, sans-serif;
взял

2020-09-24 19:35 UTC, opg-x commented on css/styles.css
> +      text-transform: none;
удалил

2020-09-24 19:38 UTC, opg-x commented on css/styles.css
> +  }
оставил

2020-09-24 19:39 UTC, opg-x commented on css/styles.css
> +      height: auto;
прописал глобальные стили

2020-09-24 19:43 UTC, opg-x commented on css/styles.css
> +      list-style-type: none;
спасибо, добавил

2020-09-24 19:46 UTC, opg-x commented on fonts/style.css
> +@font-face {
был лишний файл в папке fonts. удалил

2020-09-24 19:46 UTC, opg-x commented on fonts/style.css
> +         url('../fonts/roboto-v20-latin_cyrillic-regular.svg#Roboto') format('svg'); /* Legacy iOS */
исправил

2020-09-24 19:49 UTC, opg-x commented on index.html
> +      <ul class="site-navigation">
исправил

2020-09-24 19:50 UTC, opg-x commented on index.html
> +      <ul class="features-itempartnership-list">
исправил

2020-09-24 19:54 UTC, opg-x commented on index.html
> +          <a href="catalog.html" class="button button-know-more">Узнать больше</a>
исправил

2020-09-24 20:04 UTC, opg-x commented on index.html
> +        <li class="item">
убрал класс li  за ненадобностью

2020-09-24 20:13 UTC, opg-x commented on index.html
> +        <ul class="our-sevices">
переименовал

2020-09-24 20:17 UTC, opg-x commented on index.html
> +        <table class="table-statistics">
исправил

2020-09-24 20:23 UTC, opg-x commented on index.html
> +          <tr class="number-row">
исправил

2020-09-24 20:25 UTC, opg-x commented on index.html
> +  <footer class="page-footer">
исправил

2020-09-24 20:33 UTC, opg-x commented on index.html
> +    <section class="footer-navigation">
убрал

2020-09-24 20:33 UTC, opg-x commented on index.html
> +        <a class="button button-write-us" href="#">Напишите нам</a>
переименовал

2020-09-24 20:39 UTC, opg-x commented on index.html
> +    <section class="footer-social">
убрал

2020-09-24 20:43 UTC, opg-x commented on css/styles.css
> +  .center h1 {
удалил стиль т.к. h1 нет в разметке страницы

2020-09-25 19:21 UTC, raccoonroman approved these changes
Принято!

2020-09-25 19:21 UTC, raccoonroman commented on css/styles.css
> +.footer-contacts h2{
```suggestion
.footer-contacts h2 {
```

2020-09-25 19:21 UTC, raccoonroman commented on css/styles.css
> +.footer-contacts p{
```suggestion
.footer-contacts p {
```

2020-09-25 19:21 UTC, raccoonroman commented on css/styles.css
> +*, *::before, *::after {
глоб. стили лучше размещать в самом верху

2020-09-25 19:21 UTC, merged

2020-09-26 08:26 UTC, opg-x commented on css/styles.css
> +.footer-contacts h2{
исправил

2020-09-26 08:26 UTC, opg-x commented on css/styles.css
> +.footer-contacts p{
исправил