стилизация внутренней страницы
htmlacademy-htmlcss/1580379-nerds-29 pull request #5
Opened 2020-09-27 12:46 UTC by opg-x

2020-09-27 20:34 UTC, raccoonroman requested changes

2020-09-27 20:34 UTC, raccoonroman commented on catalog.html
>            <img src="#" alt="Картинка сайта для туристов в городе Седона" />
карточку шаблона лучше обернуть в тег article и задать класс `template-card`.

2020-09-27 20:34 UTC, raccoonroman commented on catalog.html
>            <img src="#" alt="Картинка сайта для туристов в городе Седона" />
каждый article будет в свое й лишке соответственно

2020-09-27 20:34 UTC, raccoonroman commented on catalog.html
> +            <h3><a href="#">SEDONA</a></h3>
внутренним элементам  карточки лучше всего задавать классы в таком стиле - `template-card-title`, `template-card-link`, `template-card-button`, `template-card-wrapper` и т. д.

2020-09-27 20:34 UTC, raccoonroman commented on css/styles.css
> +  background-color: var(--coral);
эти стили - красный фон в покое, наведении, нажатии можно считать общими для всех кнопок, а потому их лучше задать классу button, вместо того, чтобы прописывать каждой кнопке отдельно. Только две кнопки на главной странице имеют другой цвет - зеленый и желтый - вот им уже нужно отдельно переопределять цвет.

2020-09-27 20:34 UTC, raccoonroman commented on css/styles.css
> +.catalog-filter-sort-item a{
```suggestion
.catalog-filter-sort-item a {
```

2020-09-27 20:34 UTC, raccoonroman commented on css/styles.css
> +  opacity: 0.3;
лучше всегда писать по возможности `color: rgba(0, 0, 0, 0.3);` чем писать цвет и задавать opacity.
Да, с кастомными переменными это к сожалению, не так удобно :/ Но на втором уровне будет удобно.

2020-09-27 20:34 UTC, raccoonroman commented on css/styles.css
> +.catalog-pagination-list a{
```suggestion
.catalog-pagination-list a {
```

2020-09-27 20:47 UTC, opg-x commented on catalog.html
> +        <li><a href="#">магазин</a></li>
судя по макету.... Страница каталога = надпись "магазин" [https://prnt.sc/uowxva](url)

2020-09-27 20:50 UTC, opg-x commented on catalog.html
> +        <li><a href="#">магазин</a></li>
судя по макету... страница каталога = надписи "магазин" в навигации. 
https://prnt.sc/uowxva

2020-09-27 20:54 UTC, opg-x commented on catalog.html
> +<body class="page-body inner-page">
убрал

2020-09-27 21:00 UTC, opg-x commented on catalog.html
> +  <main class="center catalog">
только за! я если честно не понял почему на лекции настоятельно рекомендовали ставить классы тегам "html" и "main" 
https://prnt.sc/uox30h
P.S. указанные классы удалил

2020-09-27 21:10 UTC, opg-x commented on catalog.html
> +    <h1 class="catalog-title">Магазин готовых шаблонов</h1>
исправил на "catalog-page-title"

2020-09-27 21:23 UTC, opg-x commented on catalog.html
>            <img src="#" alt="Картинка сайта для туристов в городе Седона" />
исправил

2020-09-27 21:28 UTC, opg-x commented on css/styles.css
> +.catalog-filter-sort-item a{
исправил

2020-09-27 21:28 UTC, opg-x commented on css/styles.css
> +.catalog-pagination-list a{
исправил

2020-09-27 21:50 UTC, opg-x commented on catalog.html
> +            <h3><a href="#">SEDONA</a></h3>
исправил

2020-09-27 22:13 UTC, opg-x commented on css/styles.css
> +  background-color: var(--coral);
сделал

2020-09-28 18:54 UTC, opg-x commented on css/styles.css
> +  opacity: 0.3;
изменил, также и в других случаях

2020-09-28 19:09 UTC, raccoonroman commented on catalog.html
> +  <main class="center catalog">
в каждого макета своя структура. Так что единого шаблона нет. Обычно на тег main никаких стилей не вешают, потому и классов ему не нужно задавать.

2020-09-28 19:12 UTC, raccoonroman commented on catalog.html
> +    <h1 class="catalog-title">Магазин готовых шаблонов</h1>
как раз таки класс `catalog-page-title` идет с привязкой на страницу каталога. Я же предлагаю назвать класс `page-title`, чтобы не было такого, что мы находимся на странице оплаты или часто задаваемых вопросов или любой другой и там был класс `catalog-page-title`

2020-09-28 19:14 UTC, raccoonroman commented on css/styles.css
> +  opacity: 0.3;
а зачем лучше писать прозрачность через rgba понятно? ;)

2020-09-28 19:17 UTC, opg-x commented on catalog.html
> +    <h1 class="catalog-title">Магазин готовых шаблонов</h1>
) теперь понял. принял

2020-09-28 19:20 UTC, opg-x commented on css/styles.css
> +  opacity: 0.3;
т.к. может быть прозрачность текста и может отдельно быть прозрачность фона?!

2020-09-28 19:22 UTC, raccoonroman requested changes

2020-09-28 19:22 UTC, raccoonroman commented on catalog.html
> +        <li><a href="#">магазин</a></li>
да, ссылка `магазин` - это страница каталога. Нужно внести исправления по комментарию выше

2020-09-28 19:22 UTC, raccoonroman commented on catalog.html
> +    <h1 class="catalog-page-title">Магазин готовых шаблонов</h1>
```suggestion
    <h1 class="page-title">Магазин готовых шаблонов</h1>
```

2020-09-28 19:22 UTC, raccoonroman commented on catalog.html
> +    <h1 class="catalog-page-title">Магазин готовых шаблонов</h1>
в предыдущем топике написал, почему лучше класс назвать так

2020-09-28 19:22 UTC, raccoonroman commented on catalog.html
> +        <a class="button footer-social-button" href="#">Мы Вконтакте</a>
Соц. сетям не нужен класс button, так как стили у ссылок уникальные и к общим кнопкам не относятся
```suggestion
        <a class="footer-social-button" href="#">Мы Вконтакте</a>
```

2020-09-28 19:22 UTC, raccoonroman commented on css/styles.css
> +  color: rgba(0, 0, 0, 0.3);
цвета нужно выносить в КС https://up.htmlacademy.ru/htmlcss/29/criteries#d30

2020-09-28 19:22 UTC, raccoonroman commented on css/styles.css
> +  color: rgba(0, 0, 0, 0.3);
https://up.htmlacademy.ru/htmlcss/29/criteries#d30

2020-09-28 19:22 UTC, raccoonroman commented on css/styles.css
> +  color: rgba(0, 0, 0, 0.6);;
https://up.htmlacademy.ru/htmlcss/29/criteries#d30

2020-09-28 19:22 UTC, raccoonroman commented on css/styles.css
> +  color: rgba(0, 0, 0, 1);
https://up.htmlacademy.ru/htmlcss/29/criteries#d30

2020-09-28 19:22 UTC, raccoonroman commented on css/styles.css
> +  color: rgba(0, 0, 0, 0.3);
https://up.htmlacademy.ru/htmlcss/29/criteries#d30

2020-09-28 19:22 UTC, raccoonroman commented on css/styles.css
> +  color: rgba(0, 0, 0, 0.3);
https://up.htmlacademy.ru/htmlcss/29/criteries#d30

2020-09-28 19:23 UTC, opg-x commented on catalog.html
> +        <li><a href="#">магазин</a></li>
убрал href, чтоб не перезагружалась страница при нажатии

2020-09-28 19:26 UTC, opg-x commented on catalog.html
> +  <main class="center catalog">
убрал классы из тегов html, main & body

2020-09-28 19:26 UTC, raccoonroman commented on css/styles.css
> +  opacity: 0.3;
задавая прозрачность через opacity, мы тем самым задаем прозрачность для фона, бордера и картинки, если есть внутри элемента или в будущем могут добавиться. А это не всегда нужно. Нужно задавать прозрачность только туда, где она необходима.

2020-09-28 19:28 UTC, opg-x commented on catalog.html
> +    <h1 class="catalog-page-title">Магазин готовых шаблонов</h1>
исправил

2020-09-28 19:29 UTC, raccoonroman commented on css/styles.css
> +  color: rgba(0, 0, 0, 1);
здесь нет прозрачности, цвет можно прописать в hex-формате

2020-09-28 20:09 UTC, opg-x commented on css/styles.css
> +  color: rgba(0, 0, 0, 0.3);
исправил по всем случаям

2020-09-28 20:26 UTC, opg-x commented on catalog.html
> +        <a class="button footer-social-button" href="#">Мы Вконтакте</a>
убрал

2020-09-29 05:43 UTC, raccoonroman requested changes

2020-09-29 05:43 UTC, raccoonroman commented on catalog.html
> -      <a href="index.html">
Здесь нужна ссылка на главную. Нужно вернуть.

2020-09-29 11:03 UTC, raccoonroman approved these changes

2020-09-29 11:04 UTC, merged