гриды главной страницы
htmlacademy-htmlcss/1580379-nerds-29 pull request #7
Opened 2020-10-06 20:23 UTC by opg-x

2020-10-07 17:38 UTC, raccoonroman commented on css/styles.css
> +  padding: 0 20px;
чтобы не писать каждый раз эти стили для центровки содержимого, создай класс `container` и используй его:
.container {
```suggestion
  width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
```
  width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}

2020-10-07 17:53 UTC, raccoonroman requested changes

2020-10-07 17:53 UTC, raccoonroman commented on css/styles.css
> +  padding: 0 20px;
чтобы не писать каждый раз эти стили для центровки содержимого, создай класс `container` и используй его:
```
.container {
  width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}
```

2020-10-07 17:53 UTC, raccoonroman commented on css/styles.css
> +  grid-template-columns: repeat(3 , 300px);
```suggestion
  grid-template-columns: repeat(3, 300px);
```

2020-10-07 17:53 UTC, raccoonroman commented on css/styles.css
> +  margin: 80px 0;
секциям всегда нужно задавать внутренние отступы, чтобы в случае, когда нужно будет добавить фон, ничего менять не пришлось.

2020-10-07 17:53 UTC, raccoonroman commented on css/styles.css
> +  grid-template-columns: repeat(4 , 1fr);
```suggestion
  grid-template-columns: repeat(4, 1fr);
```

2020-10-07 17:53 UTC, raccoonroman commented on css/styles.css
> +  display: grid;
здесь больше флексы бы подошли

2020-10-07 21:01 UTC, opg-x commented on css/styles.css
> +  padding: 0 20px;
заиспользовал

2020-10-07 21:05 UTC, opg-x commented on css/styles.css
> +  grid-template-columns: repeat(3 , 300px);
исправил

2020-10-07 21:07 UTC, opg-x commented on css/styles.css
> +  grid-template-columns: repeat(4 , 1fr);
исправил

2020-10-07 21:08 UTC, opg-x commented on css/styles.css
> +  display: grid;
пока пишу только на гридах, флексы после этой домашки будут

2020-10-07 21:18 UTC, opg-x commented on css/styles.css
> +  margin: 80px 0;
пофиксил для всех случаев

2020-10-08 16:52 UTC, raccoonroman requested changes
В этом задании нужно было сетку сделать только для главной страницы.

2020-10-08 16:52 UTC, raccoonroman commented on catalog.html
>      <h1 class="page-title">Магазин готовых шаблонов</h1>
заголовок тоже должен быть в своем контейнере, так как когда текста будет больше, он не должен выходить за границы максимальной ширины контента

2020-10-08 16:52 UTC, raccoonroman commented on index.html
> +      <section class="features container">
желательно, чтобы контейнер имел свой тег (div) и не совмещался с другими классами. Так не будут перебиваться стили и меньше вероятность, что что-то пойдет не так. К тому же так делает популярная библиотека `bootstrap`.
Сделай так: 
```
<section class="features">
   <div class="container"> ...
```
и внешняя обертка `features-wrapper` не нужна будет

2020-10-08 16:54 UTC, raccoonroman commented
И, кстати, это наиболее универсальный способ, когда, контейнер идет внутри каждой секции: `.section>.container>.content`, так как бывает нужно всей секции задать какой-то фон, и при этом не придется перестраивать разметку.

2020-10-08 17:07 UTC, opg-x commented on catalog.html
>      <h1 class="page-title">Магазин готовых шаблонов</h1>
исправлю как дойдем до каталога

2020-10-08 17:15 UTC, opg-x commented on index.html
> +      <section class="features container">
понял, принял, сделал

2020-10-09 06:19 UTC, raccoonroman approved these changes

2020-10-09 06:20 UTC, merged